### PR TITLE
Initialise the chunkSize during iterator construction

### PR DESCRIPTION
**Pull request by sreekanth-cb**
getChunkSize call involve calls to GetCardinality
of the roaring which is costly. Hence making this
chunkSize initialisation as a part of the iterator
creation to save the multiple getChunkSize call
overheads during a postings' navigation.

### CODE REVIEW

**Review by mschoch — CHANGES_REQUESTED** [review]
I dislike the way we initialize this now and can't properly handle the error.  And then we have to check for a 0 value on every use.

Why not move the initialization all the way up to when we first create the postings list (the list itself, not the iterator)?  We should have everything we need at that point, and those methods can return the error directly.

Second, your commit message implies this has performance implications.  Can you share more about how you found it, and how much impact this change has?

**Comment by sreekanth-cb** [comment]
I don't have the precise number improvements against the latest v14 format.. But in my experimental toy builds it showed an improvements of more than 50 qps in a showfast test.

Before this fix, these calls made footprints in the profile.

Screenshot 2020-07-06 at 5 07 48 PM

**Comment by sreekanth-cb** [comment]
hm..., think I need to add such chunkSize initialisations in postingsListInit() methods as well.

**Comment by mschoch** [comment]
Yeah the code is quite complicated because of attempts to reuse data structures.  We have like several places that create postings list.  I recommend you search for all postings list literals.

**Comment by sreekanth-cb** [comment]
yea...will check that further.. As of now, it looks like false alarm.

**Comment by mschoch** [comment]
Hmmn, ok.  When I reviewed the code and made the suggestion, I was thinking the code was going somewhere else (don't remember where now).  So I'll have to review it all again closer as well.

**Comment by sreekanth-cb** [comment]
hey @mschoch , you had some comments here regarding the initialisations, right?

**Comment by mschoch** [comment]
@sreekanth-cb you commented that you would check further, but no new commits or comments about that ever showed up.

**Comment by sreekanth-cb** [comment]
@mschoch , my earlier doubt was whether we need to add similar initialisations here as well -https://github.com/blevesearch/zap/blob/master/dict.go#L80 in postingsListInit function. 

But it looks like this code path isn't applicable for the chunkSize initialisations as this function looks more of a memory reset before the actual initialisations of the postings.  Actual postings initialisations still happens over the read() call is my understanding. ( ref - https://github.com/blevesearch/zap/blob/master/dict.go#L72)

In postingsListFromOffset happy case scenario,  the postingsListInit call is followed by a read() call to let the chunkSize initialisations.

I am unable to see any other cases here.

**Review by mschoch — APPROVED** [review]

**Pull request merged**
