### PR TITLE
Improve the reuse of the chunkedIntCoders in postings

### PR DESCRIPTION
**Pull request by sreekanth-cb**

### CODE REVIEW

**Comment by sreekanth-cb** [comment]
This has brought in a nice 12%+ performance improvement in the QPS in a single node on z14 format.

High freq qps on a single node.

495 Vs 557(re use fix)

Low freq qps on a single node.

24156 Vs 26762 (re use fix)

**Review by mschoch — CHANGES_REQUESTED** [review]
Don't we end up calling Reset twice now?

It seems like they get reset here:

https://github.com/blevesearch/zap/blob/master/posting.go#L162
https://github.com/blevesearch/zap/blob/master/posting.go#L167

And then again inside newChunkedIntDecoder.

Also, why the change to the isNil() method?  It doesn't seem directly related to the other changes.

**Comment by sreekanth-cb** [comment]
>Don't we end up calling Reset twice now?

Yes, that is right. Felt without the reset inside this function it looks incomplete as the function as such could be called with a non reseted postingsList by the user. Perhaps I can add comments to the function that it expects a reseted postingsList and save the extra calling.

>Also, why the change to the isNil() method?

As a part of the reset, we reset the length of the internal buffers but not make them as nil. So this check was turning to be in effective and was causing crashes later on during the use of a re used postingsList.

**Review by mschoch — CHANGES_REQUESTED** [review]
I guess my concern is that it still feels backwards.  Why do we call newChunkedIntDecoder, when we already have an instance (passed in as the new argument).  Couldn't we just have a proper reset method that allows for reuse?

**Comment by sreekanth-cb** [comment]
> I guess my concern is that it still feels backwards. Why do we call newChunkedIntDecoder, when we already have an instance (passed in as the new argument). Couldn't we just have a proper reset method that allows for reuse?

oops..I couldn't follow your point here. From what I understood, this situation is same as what is happening with an Iterator function? https://github.com/blevesearch/zap/blob/master/posting.go#L157. User optionally pass a prealloced object for reuse.
If we rename the newChunkedIntDecoder to chunkedIntDecoder() would this be ok ?

**Comment by mschoch** [comment]
My concern is that a method named `NewXYZ` should create a new XYZ when you don't have one.  If you have an existing XYZ that you want to reuse, I would expect you could simply call XYZ.Reset(). 

Now, you're right, sometimes we have cases where the calling code isn't sure.  It has a pointer to an XYZ, but that might be nil because it hasn't been initialized.  In those cases we sometimes have methods like iterator() you linked to.  It creates a New thing or optionally reuses an existing one.

My concern though is that is NOT the case here.  On postings.go line 209, `rv.freqNormReader` will always be non-nil.  So, in that case it seems wrong or lazy to call NewXYZ, because it's unnecessary, we know XYZ isn't nil, we should just reset it right?

**Comment by sreekanth-cb** [comment]
> On postings.go line 209, `rv.freqNormReader` will always be non-nil.

I was doubtful on this, esp when there were no pre alloc-ed PostingsIterator.  ref - https://github.com/blevesearch/zap/blob/master/posting.go#L160.

**Comment by mschoch** [comment]
Ah, ok, you're right.

**Review by mschoch — APPROVED** [review]

**Pull request merged**
